USE [master]
GO

/****** Object:  Database [SISCOVE]    Script Date: 4/1/2021 09:50:53 ******/
CREATE DATABASE [SISCOVE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SISCOVE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\SISCOVE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SISCOVE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\SISCOVE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SISCOVE] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SISCOVE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SISCOVE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SISCOVE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SISCOVE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SISCOVE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SISCOVE] SET ARITHABORT OFF 
GO

ALTER DATABASE [SISCOVE] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SISCOVE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SISCOVE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SISCOVE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SISCOVE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SISCOVE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SISCOVE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SISCOVE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SISCOVE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SISCOVE] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SISCOVE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SISCOVE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SISCOVE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SISCOVE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SISCOVE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SISCOVE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SISCOVE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SISCOVE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SISCOVE] SET  MULTI_USER 
GO

ALTER DATABASE [SISCOVE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SISCOVE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SISCOVE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SISCOVE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SISCOVE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SISCOVE] SET QUERY_STORE = OFF
GO

USE [SISCOVE]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SISCOVE] SET  READ_WRITE 
GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 4/1/2021 09:51:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[ID_CUSTOMERS] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[TEL1] [nvarchar](50) NOT NULL,
	[TEL2] [nvarchar](50) NOT NULL,
	[TEL3] [nvarchar](50) NOT NULL,
	[RUC] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CUSTOMERS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Distributors]    Script Date: 4/1/2021 09:51:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Distributors](
	[ID_DISTRIBUTORS] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[TEL1] [nvarchar](50) NOT NULL,
	[TEL2] [nvarchar](50) NOT NULL,
	[TEL3] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_DISTRIBUTORS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Orders]    Script Date: 4/1/2021 09:51:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Orders](
	[ID_ORDERS] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT] [nvarchar](50) NOT NULL,
	[CUSTOMER] [nvarchar](50) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[SITUATION] [int] NOT NULL,
	[DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ORDERS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Password]    Script Date: 4/1/2021 09:52:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Password](
	[ID_PASSWORD] [int] IDENTITY(1,1) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[CODE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PASSWORD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Purchases]    Script Date: 4/1/2021 09:52:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Purchases](
	[ID_PURCHASES] [int] IDENTITY(1,1) NOT NULL,
	[ID_STOCK] [int] NOT NULL,
	[ID_DISTRIBUTORS] [int] NOT NULL,
	[PRICE] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[DATE] [datetime] NOT NULL,
	[F] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PURCHASES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Sales]    Script Date: 4/1/2021 09:52:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales](
	[ID_SALES] [int] IDENTITY(1,1) NOT NULL,
	[ID_STOCK] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[DATE] [datetime] NOT NULL,
	[F] [int] NOT NULL,
	[PRICE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_SALES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [SISCOVE]
GO

/****** Object:  Table [dbo].[Stock]    Script Date: 4/1/2021 09:52:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stock](
	[ID_STOCK] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT] [nvarchar](100) NOT NULL,
	[PRICE1] [int] NOT NULL,
	[PRICE2] [int] NOT NULL,
	[PRICE3] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[WARNING] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_STOCK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

